# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [25]:
s="Hi there Sam!"
x=s.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [7]:
planet = "Earth"
diameter = 12742

In [8]:
print('The diameter of {planet} is {diameter} kilometers.'.format(planet="Earth",diameter=12742))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [9]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [10]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [11]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [12]:
import numpy as np
array_1=np.zeros(10)
print("An array of 10 zeros:")
print(array_1)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
import numpy as np
array_2=np.ones(10)*5
print("An array of 10 fives:")
print(array_2)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [15]:
import numpy as np
even=np.arange(20,35,2)
print("An array of all the even integers from 20 to 35:")
print(even)

An array of all the even integers from 20 to 35:
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
import numpy as np
matrix=np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [18]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
Join=np.concatenate((a,b),axis=None)
print(Join)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [19]:
import pandas as pd


In [21]:
import pandas as pd
data={'Highest_Mountains':['Mount Everest','Kangchenjunga','K2'],'Height':[8848,8586,8611]}
df=pd.DataFrame(data)
print(df)

  Highest_Mountains  Height
0     Mount Everest    8848
1     Kangchenjunga    8586
2                K2    8611


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [22]:
from datetime import timedelta,date
def daterange(date1,date2):
  for n in range(int((date2-date1).days)+1):
    yield date1 + timedelta(n)

start_dt=date(2023,1,1)
end_dt=date(2023,2,10)
for dt in daterange(start_dt,end_dt):
  print(dt.strftime("%d-%m-%y"))


01-01-23
02-01-23
03-01-23
04-01-23
05-01-23
06-01-23
07-01-23
08-01-23
09-01-23
10-01-23
11-01-23
12-01-23
13-01-23
14-01-23
15-01-23
16-01-23
17-01-23
18-01-23
19-01-23
20-01-23
21-01-23
22-01-23
23-01-23
24-01-23
25-01-23
26-01-23
27-01-23
28-01-23
29-01-23
30-01-23
31-01-23
01-02-23
02-02-23
03-02-23
04-02-23
05-02-23
06-02-23
07-02-23
08-02-23
09-02-23
10-02-23


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [23]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [24]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists,columns=['SI.NO','NAME','AGE'])
print(df)

   SI.NO NAME  AGE
0      1  aaa   22
1      2  bbb   25
2      3  ccc   24
